# Generated by Django 6.0.1 on 2026-07-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(help_text='세션 ID 또는 닉네임 (session/nickname).', max_length=120)),
                ('prompt', models.TextField(help_text='참가자가 제출한 프롬프트.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('queued', '대기 중'), ('generating', '코드 생성 중'), ('scoring', '채점 중'), ('done', '완료'), ('failed', '실패'), ('rate_limited', '생성 제한 대기')], db_index=True, default='queued', max_length=16)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, default='', max_length=32)),
                ('pass_fail', models.CharField(blank=True, default='', max_length=16)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('generation_retries', models.IntegerField(default=0)),
                ('scoring_retries', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('workdir', models.CharField(blank=True, default='', max_length=1024)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_finished_at', models.DateTimeField(blank=True, null=True)),
                ('scoring_started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['submitted_at'],
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='submissions_status_37dcdc_idx')],
            },
        ),
    ]
