# Generated by Django 6.0.6 on 2026-07-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_critical_penalties_submission_raw_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='regrade_only',
            field=models.BooleanField(default=False),
        ),
    ]
