# Generated by Django 6.0.6 on 2026-07-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_regrade_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['submitted_at'], 'verbose_name': '제출', 'verbose_name_plural': '제출'},
        ),
    ]
