# Generated by Django 6.0.6 on 2026-07-15 14:42

from django.db import migrations, models


def _seed_singleton(apps, schema_editor):
    GraderSettings = apps.get_model('submissions', 'GraderSettings')
    GraderSettings.objects.get_or_create(pk=1, defaults={'codex_model': ''})


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_submission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codex_model', models.CharField(blank=True, default='', help_text='Codex 모델 ID. 비우면 config/scoring.yaml 값(또는 ChatGPT 계정 기본 모델)을 사용.', max_length=120)),
            ],
            options={
                'verbose_name': '채점기 설정',
                'verbose_name_plural': '채점기 설정',
            },
        ),
        migrations.RunPython(_seed_singleton, migrations.RunPython.noop),
    ]
