# Generated by Django 6.0.6 on 2026-07-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_gradersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradersettings',
            name='codex_max_sessions',
            field=models.PositiveIntegerField(default=5, help_text='동시에 실행할 최대 Codex 생성 세션 수 (병렬 생성 상한). config의 orchestrator.generation_concurrency(풀 크기)까지만 유효.'),
        ),
    ]
