# Generated by Django 6.0.6 on 2026-07-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_gradersettings_codex_max_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradersettings',
            name='codex_reasoning_effort',
            field=models.CharField(blank=True, default='', help_text='Codex 추론 강도. 비우면 모델 기본값(default_reasoning_level)을 사용.', max_length=32),
        ),
    ]
