# Generated by Django 6.0.6 on 2026-07-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_gradersettings_codex_reasoning_effort'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='boot_log',
            field=models.TextField(blank=True, default=''),
        ),
    ]
